project:
  type: website
  output-dir: docs
  resources: files

website:
  title: "Sian Wood"
  favicon: logo.png
  site-url: https://github.com/sian-wood/sians_website
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Education
        href: education.qmd
      - text: Talks
        href: talks.qmd  
      - text: Blog posts
        href: blog.qmd
      #- text: Publications
      #  href: publications.qmd  
    right:
      - icon: github
        href: https://github.com/      

body-footer: | 
  Copyright:  Sian Wood, 2025

date-format: "D MMMM YYYY"

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true

